version: "3"
services:
  react-app:
    image: vendordash:test
    container_name: vendordash:test
    ports:
      - "4300:3000"
    volumes:
      - /home/hp/VendorDashboard:/app
    command: npm start -- --host 0.0.0.0 --port 4300
