    image: node:20-alpine
    container_name: vendor-frontend
    working_dir: /app
    volumes:
      - /home/hp/VendorDashboard:/app
    ports:
      - "4400:3000"
    command: ["npm", "start", "--host", "0.0.0.0"]